aliyun:
    oss:
        bucketName: wei-springboot-tlias-crud
        endpoint: https://oss-cn-beijing.aliyuncs.com
logging:
    level:
        org:
            springframework:
                jdbc:
                    support:
                        JdbcTransactionManager: debug
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123
        url: jdbc:mysql://localhost:3306/tlias
        username: root
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 100MB
